import React from "react";

const levels = ["foundational", "understanding", "application", "analysis", "challenge"];
const levelNames = ["Basic recall", "Foundational understanding", "Simple application", "Concept distinction / misconception", "Reasoning / transfer"];
const emptyResource = () => ({ title: "", url: "", provider: "", description: "", focus: "" });
const emptyQuestion = (index, objectiveId) => ({ id: `Q${index + 1}`, objective_id: objectiveId || "", difficulty: levels[index], question: "", concept: "", material_reference: "", hint: "", options: ["", "", "", ""], correct_index: 0, explanation: "", distractor_misconceptions: ["", "", "", ""], reasoning_rubric: [] });
const emptyPractice = () => ({ prompt: "", hint: "", concept: "", rubric: [] });

export function ResourceEditor({ resources, update }) {
  return <><div className="panel-title"><h3>Approved study resources</h3><button type="button" className="secondary" disabled={resources.length >= 5} onClick={() => update([...resources, emptyResource()])}>Add resource</button></div>{resources.map((resource, index) => <div className="config-item" key={index}><div className="field-grid">{["title", "url", "provider"].map(field => <label key={field}>{field === "url" ? "HTTPS link" : field === "provider" ? "Publisher" : "Resource title"}<input type={field === "url" ? "url" : "text"} value={resource[field] || ""} onChange={event => update(resources.map((item, i) => i === index ? { ...item, [field]: event.target.value } : item))} /></label>)}</div>{["description", "focus"].map(field => <label key={field}>{field === "description" ? "Brief description" : "What students should focus on"}<textarea value={resource[field] || ""} onChange={event => update(resources.map((item, i) => i === index ? { ...item, [field]: event.target.value } : item))} /></label>)}<button type="button" className="danger-link" onClick={() => update(resources.filter((_, i) => i !== index))}>Remove resource</button></div>)}</>;
}

function RubricEditor({ rubric, update, label = "Assessment criteria" }) {
  return <div className="rubric-editor"><div className="panel-title"><h4>{label}</h4><button type="button" className="secondary" onClick={() => update([...rubric, { description: "", evidence_groups: [] }])}>Add criterion</button></div>{rubric.map((criterion, index) => <div className="config-item" key={index}><label>What must the student demonstrate?<input value={criterion.description} onChange={event => update(rubric.map((item, i) => i === index ? { ...item, description: event.target.value } : item))} /></label><label>Evidence phrases for local assessment (optional)<textarea value={(criterion.evidence_groups || []).map(group => group.join(" | ")).join("\n")} placeholder="One essential idea per line; separate equivalent phrases with |" onChange={event => update(rubric.map((item, i) => i === index ? { ...item, evidence_groups: event.target.value.split("\n").filter(line => line.trim()).map(line => line.split("|").map(term => term.trim()).filter(Boolean)) } : item))} /></label><small>Without evidence phrases, this criterion needs AI assessment or instructor review. Wording alone is not a substitute for a semantic rubric.</small><button type="button" className="danger-link" onClick={() => update(rubric.filter((_, i) => i !== index))}>Remove criterion</button></div>)}</div>;
}

export default function LessonConfigEditor({ plan, update }) {
  const objectives = plan.objectives || [];
  const quiz = plan.diagnostic_quiz?.length === 5 ? plan.diagnostic_quiz : levels.map((_, index) => emptyQuestion(index, objectives[index < 2 ? 0 : Math.min(1, objectives.length - 1)]?.id));
  const assets = objectives.map(objective => plan.learning_assets?.find(item => item.objective_id === objective.id) || { objective_id: objective.id, explanation: "", worked_example: "", analogy: "", counterexample: "", foundational: [emptyPractice(), emptyPractice()], standard: [emptyPractice(), emptyPractice()], accelerated: [emptyPractice(), emptyPractice()], misconceptions: [] });
  const updateQuiz = (index, patch) => update({ diagnostic_quiz: quiz.map((item, i) => i === index ? { ...item, ...patch } : item) });
  const updateAsset = (index, patch) => update({ learning_assets: assets.map((item, i) => i === index ? { ...item, ...patch } : item) });
  return <>
    <section className="panel"><p className="step">Lesson material</p><div className="field-grid"><label>Topic<input value={plan.topic || ""} onChange={event => update({ topic: event.target.value })} /></label><label>Intended difficulty<input value={plan.intended_difficulty || ""} onChange={event => update({ intended_difficulty: event.target.value })} /></label></div><label>Prerequisite knowledge (write “none” if appropriate)<textarea value={plan.prerequisite_knowledge || ""} onChange={event => update({ prerequisite_knowledge: event.target.value })} /></label><label>Brief introductory explanation<textarea value={plan.topic_introduction || ""} onChange={event => update({ topic_introduction: event.target.value })} /></label><label>Introductory example from your material<textarea value={plan.introductory_example || ""} onChange={event => update({ introductory_example: event.target.value })} /></label><label>Approved teaching material<textarea className="teaching-material" value={plan.approved_material || ""} onChange={event => update({ approved_material: event.target.value })} placeholder="Paste the material that students can learn and that all assessments should use." /></label><ResourceEditor resources={plan.study_resources || []} update={study_resources => update({ study_resources })} /></section>
    <section className="panel"><p className="step">Objective rubrics</p>{objectives.map((objective, index) => <div className="config-item" key={objective.id}><h3>{objective.title || objective.id}</h3><RubricEditor rubric={objective.rubric || []} update={rubric => update({ objectives: objectives.map((item, i) => i === index ? { ...item, rubric } : item) })} /><h4>Identifiable misconceptions</h4>{(objective.misconceptions || []).map((misconception, mIndex) => <div key={mIndex}><label>Misconception description<input value={misconception.description} onChange={event => update({ objectives: objectives.map((item, i) => i === index ? { ...item, misconceptions: item.misconceptions.map((m, j) => j === mIndex ? { ...m, description: event.target.value } : m) } : item) })} /></label><label>Misconception phrases (one per line)<textarea value={misconception.evidence_phrases.join("\n")} onChange={event => update({ objectives: objectives.map((item, i) => i === index ? { ...item, misconceptions: item.misconceptions.map((m, j) => j === mIndex ? { ...m, evidence_phrases: event.target.value.split("\n").filter(Boolean) } : m) } : item) })} /></label><label>Respectful counterexample<textarea value={misconception.counterexample} onChange={event => update({ objectives: objectives.map((item, i) => i === index ? { ...item, misconceptions: item.misconceptions.map((m, j) => j === mIndex ? { ...m, counterexample: event.target.value } : m) } : item) })} /></label></div>)}<button type="button" className="secondary" onClick={() => update({ objectives: objectives.map((item, i) => i === index ? { ...item, misconceptions: [...(item.misconceptions || []), { description: "", evidence_phrases: [], counterexample: "" }] } : item) })}>Add misconception</button></div>)}</section>
    <section className="panel"><p className="step">Common diagnostic · prepared once per lesson</p><p>All students receive these same five questions. Check that the final question uses only concepts students have had an opportunity to learn.</p>{quiz.map((question, index) => <details className="config-item" key={question.id} open={index === 0}><summary>Question {index + 1} · {levelNames[index]}</summary><label>Question<textarea value={question.question} onChange={event => updateQuiz(index, { question: event.target.value })} /></label><div className="field-grid"><label>Learning objective<select value={question.objective_id} onChange={event => updateQuiz(index, { objective_id: event.target.value })}>{objectives.map(objective => <option key={objective.id} value={objective.id}>{objective.title || objective.id}</option>)}</select></label><label>Relevant concept<input value={question.concept || ""} onChange={event => updateQuiz(index, { concept: event.target.value })} /></label></div><label>Relevant section of approved material<input value={question.material_reference || ""} onChange={event => updateQuiz(index, { material_reference: event.target.value })} /></label>{question.options.map((option, optionIndex) => <div className="field-grid" key={optionIndex}><label>Option {String.fromCharCode(65 + optionIndex)}<input value={option} onChange={event => updateQuiz(index, { options: question.options.map((item, i) => i === optionIndex ? event.target.value : item) })} /></label><label>{question.correct_index === optionIndex ? "Correct option" : "Misconception represented by this distractor"}<input disabled={question.correct_index === optionIndex} value={question.distractor_misconceptions?.[optionIndex] || ""} onChange={event => updateQuiz(index, { distractor_misconceptions: question.options.map((_, i) => i === optionIndex ? event.target.value : question.distractor_misconceptions?.[i] || "") })} /></label></div>)}<label>Authoritative correct answer<select value={question.correct_index} onChange={event => updateQuiz(index, { correct_index: Number(event.target.value) })}>{question.options.map((_, optionIndex) => <option value={optionIndex} key={optionIndex}>{String.fromCharCode(65 + optionIndex)}</option>)}</select></label><label>Explanation of the correct answer<textarea value={question.explanation} onChange={event => updateQuiz(index, { explanation: event.target.value })} /></label><label>Conceptual hint that does not reveal the answer<textarea value={question.hint || ""} onChange={event => updateQuiz(index, { hint: event.target.value })} /></label>{index >= 3 && <RubricEditor label="One-sentence reasoning rubric" rubric={question.reasoning_rubric || []} update={reasoning_rubric => updateQuiz(index, { reasoning_rubric })} />}</details>)}</section>
    <section className="panel"><p className="step">Approved explanations and fresh practice</p>{assets.map((asset, index) => <details className="config-item" key={asset.objective_id}><summary>{objectives[index]?.title || asset.objective_id}</summary>{["explanation", "worked_example", "counterexample", "analogy"].map(field => <label key={field}>{field.replaceAll("_", " ")}{field === "analogy" ? " (optional simplified comparison)" : ""}<textarea value={asset[field] || ""} onChange={event => updateAsset(index, { [field]: event.target.value })} /></label>)}{["foundational", "standard", "accelerated"].map(level => <div key={level}><h4>{level === "foundational" ? "Simpler activities" : level === "standard" ? "Application activities" : "Transfer challenges"}</h4>{asset[level].map((activity, activityIndex) => <div className="config-item" key={activityIndex}><label>Fresh activity {activityIndex + 1}<textarea value={activity.prompt} onChange={event => updateAsset(index, { [level]: asset[level].map((item, i) => i === activityIndex ? { ...item, prompt: event.target.value } : item) })} /></label><label>Relevant diagnostic concept<input value={activity.concept || ""} onChange={event => updateAsset(index, { [level]: asset[level].map((item, i) => i === activityIndex ? { ...item, concept: event.target.value } : item) })} /></label><label>Hint<textarea value={activity.hint} onChange={event => updateAsset(index, { [level]: asset[level].map((item, i) => i === activityIndex ? { ...item, hint: event.target.value } : item) })} /></label><RubricEditor label="Activity rubric (leave empty to use the objective rubric)" rubric={activity.rubric || []} update={rubric => updateAsset(index, { [level]: asset[level].map((item, i) => i === activityIndex ? { ...item, rubric } : item) })} /><button type="button" className="danger-link" disabled={asset[level].length <= 2} onClick={() => updateAsset(index, { [level]: asset[level].filter((_, i) => i !== activityIndex) })}>Remove activity</button></div>)}<button type="button" className="secondary" disabled={asset[level].length >= 5} onClick={() => updateAsset(index, { [level]: [...asset[level], emptyPractice()] })}>Add activity</button></div>)}</details>)}</section>
    <section className="panel"><label className="check"><input type="checkbox" checked={!!plan.content_approved} onChange={event => update({ content_approved: event.target.checked })} /><span>I have reviewed the material, objectives, resources, questions, answer keys, and rubrics. The lesson assesses only concepts taught in these materials.</span></label></section>
  </>;
}
